name:                bash-script
version:             0.1.0.0
github:              "deepflowinc/hs-bash-script"
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

tested-with:
- GHC == 9.2.8
- GHC == 9.4.8
- GHC == 9.6.4
- GHC == 9.8.1

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A Haskell library for generating bash scripts
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc/hs-bash-script#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - bytestring
  - neat-interpolation
  - semigroupoids
  - shell-escape
  - text

tests:
  bash-script-test:
    source-dirs: test
    main: Test.hs
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bash-script
